/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_7f0d90fb (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/fwltshzniolrekqhtpgv/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "@supabase/supabase-js";

const client = () => createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7f0d90fb").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client();
    if (!supabase) {
      throw new Error('Failed to initialize Supabase client - check SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
    }
    
    const { data, error } = await supabase.from("kv_store_7f0d90fb").select("value").eq("key", key).maybeSingle();
    if (error) {
      throw new Error(`KV Store get error for key "${key}": ${error.message}`);
    }
    return data?.value;
  } catch (error) {
    console.error(`[KV Store] get("${key}") error:`, error);
    throw error;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7f0d90fb").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7f0d90fb").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_7f0d90fb").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_7f0d90fb").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix - returns array of KEYS (not values)
export const getByPrefix = async (prefix: string): Promise<string[]> => {
  try {
    const supabase = client();
    if (!supabase) {
      throw new Error('Failed to initialize Supabase client - check SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
    }
    
    const { data, error} = await supabase.from("kv_store_7f0d90fb").select("key, value").like("key", prefix + "%");
    if (error) {
      throw new Error(`KV Store getByPrefix error for prefix "${prefix}": ${error.message}`);
    }
    // Return keys, not values - caller will use kv.get(key) to fetch values
    return data?.map((d) => d.key) ?? [];
  } catch (error) {
    console.error(`[KV Store] getByPrefix("${prefix}") error:`, error);
    throw error;
  }
};

