/**
 * Build script for serverless function
 * Bundles server code using esbuild for optimal serverless deployment
 */

import { build } from 'esbuild';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

const packageJson = JSON.parse(
  readFileSync(join(rootDir, 'package.json'), 'utf-8')
);

async function buildServer() {
  try {
    await build({
      entryPoints: [join(rootDir, 'api/server.ts')],
      bundle: true,
      outfile: join(rootDir, 'api/server.js'),
      platform: 'node',
      target: 'node20',
      format: 'esm',
      sourcemap: false,
      minify: false,
      external: [
        // Keep these as external dependencies (Vercel provides them)
        '@supabase/supabase-js',
        '@jsr/supabase__supabase-js',
        'hono',
        'hono/cors',
        'hono/logger',
        'hono/vercel',
        '@hono/node-server',
        'dotenv',
      ],
      // Resolve TypeScript imports correctly
      resolveExtensions: ['.ts', '.tsx', '.js', '.jsx'],
      // Tree shaking
      treeShaking: true,
      banner: {
        js: `
// @ts-nocheck
// This file is auto-generated by esbuild
// Do not edit directly - edit source files in src/server/
        `.trim(),
      },
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      logLevel: 'info',
    });

    console.log('✅ Server bundled successfully');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

buildServer();

