// Placeholder file for Vercel to detect serverless function
// This file will be overwritten by esbuild during build (npm run build:server)
// Do not edit this file manually - edit source files in src/server/

export default async function handler(req, res) {
  return new Response("Server is building...", { status: 503 });
}
