/**
 * Placeholder file - will be overwritten by build script
 * This file exists so Vercel can detect the function during build
 * The actual bundled code will be generated by scripts/build-server.js
 */

// Temporary placeholder - will be replaced during build
export default async function handler() {
  return new Response('Server is building...', { status: 503 });
}

